##
## EPITECH PROJECT, 2019
## Makefile
## File description:
## makefile
##

SRC	=	utilities.c	\
		countwords.c	\
		error.c

$(NAME):	all

all:
	gcc $(SRC) -o countwords

clean:
	rm countwords

fclean:	clean

re:	fclean all
