##
## EPITECH PROJECT, 2018
## Make file
## File description:
## clean rule
##

all:
	@make -C nibbler/
	@make -C pac-man/
	@make -C space_invader/
	@make -C mainmenu/

clean:
	@make clean -C nibbler/
	@make clean -C space_invader/
	@make clean -C pac-man/
	@make clean -C mainmenu/

fclean:
	@make fclean -C nibbler/
	@make fclean -C space_invader/
	@make fclean -C pac-man/
	@make fclean -C mainmenu/

re: fclean all

.PHONY: clean re fclean all
