##
## EPITECH PROJECT, 2018
## Make file
## File description:
## clean rule
##

all:
	@make -C ncurses/
	@make -C sfml/
	@make -C caca/
	@make -C sdl/

clean:
	@make clean -C ncurses/
	@make clean -C sfml/
	@make clean -C caca/
	@make clean -C sdl/

fclean:
	@make fclean -C ncurses/
	@make fclean -C sfml/
	@make fclean -C caca/
	@make fclean -C sdl/

re: fclean all

.PHONY: clean re fclean all
