##
## EPITECH PROJECT, 2019
## makefile
## File description:
## makefile
##

all:
	@make bonus -C ../
fclean:
	@make fclean -C ../
re:
	@make fclean -C ../
	@make bonus -C ../

.PHONY:	all clean fclean re
